"""Añadir campo estado a jornada

Revision ID: 50e48fd68d5f
Revises: 
Create Date: 2025-06-05 22:27:45.434775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e48fd68d5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jornada', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
