"""Add tipo to Ausencia

Revision ID: 584f7ef38655
Revises: 868cb808ea21
Create Date: 2025-06-06 17:59:21.903654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584f7ef38655'
down_revision = '868cb808ea21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ausencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=False, server_default='otro'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ausencia', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
