"""Add estado to Ausencia

Revision ID: 868cb808ea21
Revises: 50e48fd68d5f
Create Date: 2025-06-06 16:08:51.895478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868cb808ea21'
down_revision = '50e48fd68d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ausencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ausencia', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
